return {
	Level = 5, MaxLevel = 15, XP = 110, RespawnTime = 10, GlobalDrops = false,
	Data = { Stats = { Attack = 12, Defense = 3, Critical = 0, Health = 120, Speed = 15 } },
	Currencies = { Gold = 14 },
	Drops = {
["Boar Tusk"] = { Chance = 65, Amount = 1 },
["Ironhide Band"] = { Chance = 7, Amount = 1 },
["Tuskguard Mantle"] = { Chance = 5, Amount = 1 },
 Wilderbone = { Chance = 40, Amount = 1 } },
}
