"""Bundle the editable Forest generators into one Studio Command Bar installer."""
import argparse
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
directory = Path(__file__).resolve().parent / "world-generators"
names = ["04_Forest.luau", "05_ForestMobModels.luau", "06_ForestSpawnsAndLighting.luau",
         "07_ForestCombatAssets.luau", "08_ForestAudit.luau"]
content = "-- Generated by tools/build_forest_installer.py. Edit the numbered sources.\n"
content += "-- Paste this complete file into Studio Command Bar with Play stopped.\n"
for name in names:
    content += f"\n-- BEGIN {name}\ndo\n{(directory / name).read_text(encoding='utf-8').rstrip()}\nend\n"
content += '\nprint("Forest v4 installation and static audit complete. Save the place and sync Common before Play.")\n'
target = directory / "09_InstallForest.luau"
if args.check:
    assert target.read_text(encoding="utf-8") == content, "Forest installer is stale; run tools/build_forest_installer.py"
    print("PASS: Forest installer matches its source generators")
else:
    target.write_text(content, encoding="utf-8")
    print(f"Built {target.name}")
