return {
	["Fang Dagger"] = { Level = 12, Gold = 75, Ingredients = { ["Wolf's Fang"] = 8, Wilderbone = 5, ["Dark Ivy"] = 3 } },
	["Briar Ring"] = { Level = 3, Gold = 25, Ingredients = { ["Dark Ivy"] = 6, Wilderbone = 2 } },
	["Hunter's Charm"] = { Level = 8, Gold = 50, Ingredients = { ["Wolf's Fang"] = 5, ["Dark Ivy"] = 4 } },
	["Ironhide Band"] = { Level = 6, Gold = 50, Ingredients = { Wilderbone = 8, ["Boar Tusk"] = 3 } },
	["Direheart Pendant"] = { Level = 15, Gold = 200, Ingredients = { ["Dire Claw"] = 4, Wilderbone = 12, ["Dark Ivy"] = 8 } },
}
