return {
	["Briar Ring"] = { Level = 3, Gold = 35, Ingredients = { ["Dark Ivy"] = 6 } },
	["Hunter's Charm"] = { Level = 6, Gold = 65, Ingredients = { ["Wolf's Fang"] = 5, ["Dark Ivy"] = 3 } },
	["Fang Dagger"] = { Level = 8, Gold = 100, Ingredients = { ["Wolf's Fang"] = 7, ["Dark Ivy"] = 4 } },
	["Ironhide Band"] = { Level = 9, Gold = 100, Ingredients = { Wilderbone = 5, ["Boar Tusk"] = 4 } },
	["Direheart Pendant"] = { Level = 15, Gold = 275, Ingredients = { ["Dire Claw"] = 3, Wilderbone = 10, ["Wolf's Fang"] = 6 } },

	["Sporeweave Mantle"] = { Level = 16, Gold = 180, Ingredients = { ["Spore Silk"] = 10 } },
	["Sporethorn Daggers"] = { Level = 18, Gold = 260, Ingredients = { ["Spore Silk"] = 8, ["Thorn Antler"] = 5 } },
	["Thornwood Blade"] = { Level = 19, Gold = 300, Ingredients = { ["Thorn Antler"] = 10, ["Spore Silk"] = 5 } },
	["Rune of Resonance"] = { Level = 21, Gold = 350, Ingredients = { ["Runic Bark"] = 6, ["Spore Silk"] = 6 } },
	["Sentinel Signet"] = { Level = 22, Gold = 400, Ingredients = { ["Runic Bark"] = 8, ["Thorn Antler"] = 6 } },
	["Runebark Vestment"] = { Level = 22, Gold = 450, Ingredients = { ["Runic Bark"] = 14, ["Spore Silk"] = 8 } },
	["Grovekeeper Charm"] = { Level = 25, Gold = 600, Ingredients = { ["Elder Heartwood"] = 5, ["Runic Bark"] = 8 } },
	["Heartwood Cleaver"] = { Level = 25, Gold = 700, Ingredients = { ["Elder Heartwood"] = 6, ["Runic Bark"] = 10 } },
}
