return {
	["Briar Ring"] = { Level = 3, Gold = 30, Ingredients = { ["Dark Ivy"] = 4 } },
	["Hunter's Charm"] = { Level = 6, Gold = 60, Ingredients = { ["Wolf's Fang"] = 4, ["Dark Ivy"] = 2 } },
	["Fang Dagger"] = { Level = 8, Gold = 90, Ingredients = { ["Wolf's Fang"] = 4, ["Dark Ivy"] = 3 } },
	["Ironhide Band"] = { Level = 8, Gold = 75, Ingredients = { Wilderbone = 4, ["Boar Tusk"] = 3 } },
	["Direheart Pendant"] = { Level = 15, Gold = 250, Ingredients = { ["Dire Claw"] = 2, Wilderbone = 8, ["Dark Ivy"] = 6 } },
 ["Sporeweave Mantle"] = { Level = 16, Gold = 220, Ingredients = { ["Spore Silk"] = 12, ["Runic Bark"] = 4 } },
 ["Thornwood Blade"] = { Level = 18, Gold = 300, Ingredients = { ["Thorn Antler"] = 10, ["Runic Bark"] = 6 } },
 ["Runebark Vestment"] = { Level = 23, Gold = 450, Ingredients = { ["Runic Bark"] = 16, ["Spore Silk"] = 8 } },
 ["Heartwood Cleaver"] = { Level = 25, Gold = 700, Ingredients = { ["Elder Heartwood"] = 8, ["Thorn Antler"] = 12 } },
}
